#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jun 11, 2026 12:22:49 AM %z  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import JuegoLigasUI_Support


_bgcolor = '#d9d9d9'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: JuegoLigasUI_Support.root.tk.call('source',
                os.path.join(_location, 'themes', 'classic.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('classic')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class PrimerPantalla:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1024x768+305+56")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("JuegoLigas")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.Titulo = tk.Label(self.top)
        self.Titulo.place(relx=0.303, rely=0.065, height=104, width=420)
        self.Titulo.configure(activebackground="#8c4596")
        self.Titulo.configure(activeforeground="#d70428")
        self.Titulo.configure(background="#d9d9d9")
        self.Titulo.configure(compound='left')
        self.Titulo.configure(cursor="fleur")
        self.Titulo.configure(disabledforeground="#a3a3a3")
        self.Titulo.configure(font="-family {Segoe UI} -size 36")
        self.Titulo.configure(foreground="black")
        self.Titulo.configure(highlightbackground="#d9d9d9")
        self.Titulo.configure(highlightcolor="#672dae")
        self.Titulo.configure(text='''JuegoLigas''')

        self.BotonSoloJugar = tk.Button(self.top)
        self.BotonSoloJugar.place(relx=0.41, rely=0.378, height=56, width=207)
        self.BotonSoloJugar.configure(activebackground="#d9d9d9")
        self.BotonSoloJugar.configure(activeforeground="#ffffff")
        self.BotonSoloJugar.configure(background="#d9d9d9")
        self.BotonSoloJugar.configure(command=lambda:JuegoLigasUI_Support.primerOpcion())
        self.BotonSoloJugar.configure(compound='left')
        self.BotonSoloJugar.configure(disabledforeground="#a3a3a3")
        self.BotonSoloJugar.configure(foreground="black")
        self.BotonSoloJugar.configure(highlightbackground="#808080")
        self.BotonSoloJugar.configure(highlightcolor="#808000")
        self.BotonSoloJugar.configure(text='''Jugar ligas pero solo imprimirlas''')

        self.BotonJugarYGuardar = tk.Button(self.top)
        self.BotonJugarYGuardar.place(relx=0.41, rely=0.247, height=56
                , width=207)
        self.BotonJugarYGuardar.configure(activebackground="#d9d9d9")
        self.BotonJugarYGuardar.configure(activeforeground="#ffffff")
        self.BotonJugarYGuardar.configure(background="#d9d9d9")
        self.BotonJugarYGuardar.configure(command=lambda:JuegoLigasUI_Support.segundaOpcion())
        self.BotonJugarYGuardar.configure(compound='center')
        self.BotonJugarYGuardar.configure(disabledforeground="#a3a3a3")
        self.BotonJugarYGuardar.configure(foreground="black")
        self.BotonJugarYGuardar.configure(highlightbackground="#808080")
        self.BotonJugarYGuardar.configure(highlightcolor="#808000")
        self.BotonJugarYGuardar.configure(text='''Jugar ligas y guardarlas''')

        _style_code()
        self.Scrolledtext1 = ScrolledText(self.top)
        self.Scrolledtext1.place(relx=0.01, rely=0.534, relheight=0.461
                , relwidth=0.979)
        self.Scrolledtext1.configure(background="#d9d9d9")
        self.Scrolledtext1.configure(exportselection="0")
        self.Scrolledtext1.configure(font="TkTextFont")
        self.Scrolledtext1.configure(foreground="black")
        self.Scrolledtext1.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext1.configure(highlightcolor="black")
        self.Scrolledtext1.configure(insertbackground="black")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="#0b0a0a")
        self.Scrolledtext1.configure(selectforeground="#ffffff")
        self.Scrolledtext1.configure(wrap="none")

    def insertTextToWidget(self, string):
        self.Scrolledtext1.insert(tk.INSERT, string)
        #self.Scrolledtext1.insert(tk.INSERT, "\n")

    def seeLastLine(self):
        self.Scrolledtext1.see("end")

class TextRedirector:
    def __init__(self, widget: PrimerPantalla):
        self.widget = widget

    def write(self, string):
        self.widget.insertTextToWidget(string)
        self.widget.seeLastLine()

    def flush(self):
        pass

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    JuegoLigasUI_Support.main()

if __name__ == '__main__':
    JuegoLigasUI_Support.main()