#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jun 11, 2026 12:22:56 AM %z  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import JuegoLigasUI
import main as program

_debug = False # False to eliminate debug printing from callback functions.
mainWidgetText = None
def mainWidgetText():
    return mainWidgetText
def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = JuegoLigasUI.PrimerPantalla(_top1)
    root.mainloop()

def primerOpcion(*args):
    program.primeraOpcion()

def segundaOpcion(*args):
    program.segundaOpcion()
    # if _debug:
    #     print('JuegoLigasUI_support.segundaOpcion')
    #     for arg in args:
    #         print ('    another arg:', arg)
    #     sys.stdout.flush()

if __name__ == '__main__':
    JuegoLigasUI.start_up()